Vagrant.configure("2") do |config|
      config.vm.define "node01" do |node01|
          node01.vm.box = "generic/rhel8"
          node01.vm.hostname = "node01"
          node01.vm.network "private_network", ip: "192.168.56.81"
          node01.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "node01"
          end
      end

      config.vm.define "node01" do |node01|
          node01.vm.box = "generic/rhel8"
          node01.vm.hostname = "node01"
          node01.vm.network "private_network", ip: "192.168.56.81"
          node01.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "node01"
          end
      end


      config.vm.define "node02" do |node02|
          node02.vm.box = "generic/debian11"
          node02.vm.hostname = "node02"
          node02.vm.network "private_network", ip: "192.168.56.82"
          node02.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node02"
          end
      end

      config.vm.define "node03" do |node03|
          node03.vm.box = "ubuntu/focal64"
          node03.vm.hostname = "node03"
          node03.vm.network "private_network", ip: "192.168.56.83"
          node03.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node03"
          end
      end

      config.vm.define "node04" do |node04|
          node04.vm.box = "generic/opensuse15"
          node04.vm.hostname = "node04"
          node04.vm.network "private_network", ip: "192.168.56.84"
          node04.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node04"
          end
      end

      config.vm.define "node05" do |node05|
          node05.vm.box = "centos/stream8"
          node05.vm.hostname = "node05"
          node05.vm.network "private_network", ip: "192.168.56.85"
          node05.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node05"
          end
      end

      config.vm.provision "ansible" do |ansible|
      ansible.playbook = "/home/eflores/git.personal/ansible/playbooks/create-user-vagrant.yml"
       ansible.host_vars = {
         "node01" => {"remove_ip" => "192.168.56.81"},
         "node02" => {"ansible_python_interpreter" => "/usr/bin/python3",
                      "remove_ip" => "192.168.56.82"},
         "node03" => {"remove_ip" => "192.168.56.83"},
         "node04" => {"remove_ip" => "192.168.56.84"},
         "node05" => {"remove_ip" => "192.168.56.85"}
       }
    end
end
