Vagrant.configure("2") do |config|
      config.vm.define "node01" do |node01|
          node01.vm.box = "generic/rhel7"
          node01.vm.hostname = "node01"
          node01.vm.network "private_network", ip: "192.168.56.81"
          node01.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "node01"
          end
      end

      config.vm.define "node02" do |node02|
          node02.vm.box = "generic/rhel8"
          node02.vm.hostname = "node02"
          node02.vm.network "private_network", ip: "192.168.56.82"
          node02.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "node02"
          end
      end

      config.vm.define "node03" do |node03|
          node03.vm.box = "generic/rhel9"
          node03.vm.hostname = "node03"
          node03.vm.network "private_network", ip: "192.168.56.83"
          node03.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "node03"
          end
      end

      config.vm.define "node04" do |node04|
          node04.vm.box = "generic/debian10"
          node04.vm.hostname = "node04"
          node04.vm.network "private_network", ip: "192.168.56.84"
          node04.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node04"
          end
      end

  
      config.vm.define "node05" do |node05|
          node05.vm.box = "generic/debian11"
          node05.vm.hostname = "node05"
          node05.vm.network "private_network", ip: "192.168.56.85"
          node05.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node05"
          end
      end
  
      config.vm.define "node06" do |node06|
          node06.vm.box = "generic/debian12"
          node06.vm.hostname = "node06"
          node06.vm.network "private_network", ip: "192.168.56.86"
          node06.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node06"
          end
      end

      config.vm.define "node07" do |node07|
          node07.vm.box = "ubuntu/bionic64"
          node07.vm.hostname = "node07"
          node07.vm.network "private_network", ip: "192.168.56.87"
          node07.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node07"
          end
      end

      config.vm.define "node08" do |node08|
          node08.vm.box = "ubuntu/focal64"
          node08.vm.hostname = "node08"
          node08.vm.network "private_network", ip: "192.168.56.88"
          node08.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node08"
          end
      end

      config.vm.define "node09" do |node09|
          node09.vm.box = "ubuntu/jammy64"
          node09.vm.hostname = "node09"
          node09.vm.network "private_network", ip: "192.168.56.89"
          node09.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node09"
          end
      end

      config.vm.define "node10" do |node10|
          node10.vm.box = "generic/centos8s"
          node10.vm.hostname = "node10"
          node10.vm.network "private_network", ip: "192.168.56.90"
          node10.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node10"
          end
      end

      config.vm.define "node11" do |node11|
          node11.vm.box = "generic/rocky8"
          node11.vm.hostname = "node11"
          node11.vm.network "private_network", ip: "192.168.56.91"
          node11.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node11"
          end
      end

      config.vm.define "node12" do |node12|
          node12.vm.box = "generic/rocky9"
          node12.vm.hostname = "node12"
          node12.vm.network "private_network", ip: "192.168.56.91"
          node12.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "node12"
          end
      end

      config.vm.provision "ansible" do |ansible|
      ansible.playbook = "/home/eflores/git.personal/ansible/playbooks/create-user-vagrant.yml"
       ansible.host_vars = {
         "node01" => {"remove_ip" => "192.168.56.81"},
         "node02" => {"ansible_python_interpreter" => "/usr/bin/python3",
                      "remove_ip" => "192.168.56.82"},
         "node03" => {"remove_ip" => "192.168.56.83"},
         "node04" => {"remove_ip" => "192.168.56.84"},
         "node05" => {"remove_ip" => "192.168.56.85"}
       }
    end
end
